import CausalGeometry.Completion.BruhatTitsContract
import Mathlib.Tactic

namespace CausalGeometry

universe u

/-- Rooted layered tree generated by one certified Bruhat--Tits branching
contract.

Depth zero is the distinguished base lattice. Depth n+1 is represented by the
finite projective sphere P¹(A_n). Children of a non-root vertex are exactly the
fiber of the next projective reduction. -/
inductive BruhatTitsRootedVertex
    {A : ℕ → Type u}
    [∀ n, CommRing (A n)]
    [∀ n, IsLocalRing (A n)]
    [∀ n, Fintype (A n)]
    (T : PrimePowerLocalRingTower A) : Type u
  | root
  | sphere (n : ℕ)
      (point : LocalProjectivePair.Line (A n))

namespace BruhatTitsRootedVertex

variable
    {A : ℕ → Type u}
    [∀ n, CommRing (A n)]
    [∀ n, IsLocalRing (A n)]
    [∀ n, Fintype (A n)]
    {T : PrimePowerLocalRingTower A}
    (B : BruhatTitsBranchingContract T)

abbrev Vertex :=
  BruhatTitsRootedVertex T

/-- Combinatorial depth from the base root. -/
def depth : Vertex (T := T) → ℕ
  | .root => 0
  | .sphere n _ => n + 1

/-- Children are represented directly, avoiding an artificial global edge
relation. -/
def Child : Vertex (T := T) → Type u
  | .root =>
      LocalProjectivePair.Line (A 0)
  | .sphere n y =>
      {x : LocalProjectivePair.Line (A (n + 1)) //
        LocalProjectivePair.map (T.drop n) x = y}

/-- Turn one child witness into the corresponding tree vertex. -/
def childVertex :
    (v : Vertex (T := T)) →
      Child (B := B) v →
        Vertex (T := T)
  | .root, x =>
      .sphere 0 x
  | .sphere n _, x =>
      .sphere (n + 1) x.1

/-- Every child lies exactly one layer deeper than its parent. -/
theorem depth_childVertex
    (v : Vertex (T := T))
    (c : Child (B := B) v) :
    depth (childVertex B v c) =
      depth v + 1 := by
  cases v with
  | root =>
      rfl
  | sphere n y =>
      rfl

/-- The distinguished root has q+1 children. -/
theorem root_child_natCard :
    Nat.card (Child (B := B) (.root : Vertex (T := T))) =
      T.q + 1 := by
  change
    Nat.card (LocalProjectivePair.Line (A 0)) =
      T.q + 1
  exact B.projective_card_zero

/-- Every non-root vertex has exactly q children. -/
theorem sphere_child_natCard
    (n : ℕ)
    (y : LocalProjectivePair.Line (A n)) :
    Nat.card
        (Child (B := B)
          (.sphere n y : Vertex (T := T))) =
      T.q := by
  exact B.reduction_fiber_card n y

/-- Sphere cardinal at rooted depth n+1. -/
theorem sphere_natCard
    (n : ℕ) :
    Nat.card
        {v : Vertex (T := T) //
          ∃ y : LocalProjectivePair.Line (A n),
            v = .sphere n y} =
      (T.q + 1) * T.q ^ n := by
  let e :
      {v : Vertex (T := T) //
        ∃ y : LocalProjectivePair.Line (A n),
          v = .sphere n y} ≃
        LocalProjectivePair.Line (A n) where
    toFun := fun v => by
      rcases v.2 with ⟨y, hy⟩
      exact y
    invFun := fun y =>
      ⟨.sphere n y, ⟨y, rfl⟩⟩
    left_inv := by
      intro v
      apply Subtype.ext
      rcases v.2 with ⟨y, hy⟩
      exact hy.symm
    right_inv := by
      intro y
      rfl
  rw [Nat.card_congr e]
  exact B.projective_card n

/-- A finite child chain records a unique outward causal/tree trajectory. -/
inductive Descendant :
    (v : Vertex (T := T)) → ℕ →
      Vertex (T := T) → Prop
  | refl (v) :
      Descendant v 0 v
  | step {v w z n}
      (c : Child (B := B) v)
      (hw : w = childVertex B v c)
      (h : Descendant w n z) :
      Descendant v (n + 1) z

theorem descendant_depth
    {v z : Vertex (T := T)}
    {n : ℕ}
    (h : Descendant (B := B) v n z) :
    depth z = depth v + n := by
  induction h with
  | refl v =>
      simp
  | @step v w z n c hw h ih =>
      subst w
      rw [ih, depth_childVertex]
      omega

end BruhatTitsRootedVertex
end CausalGeometry
