import CausalGeometry.Models.ExchangePersistentControls

/-! Requires actual Lean; this is not a transcript of its execution. -/
#print axioms CausalGeometry.LinearInvariant.mem_core
#print axioms CausalGeometry.LinearInvariant.core_le
#print axioms CausalGeometry.LinearInvariant.core_stable
#print axioms CausalGeometry.LinearInvariant.le_core
#print axioms CausalGeometry.LinearInvariant.core_mono
#print axioms CausalGeometry.LinearInvariant.core_eq_of_stable
#print axioms CausalGeometry.LinearInvariant.stable_iff_core_eq
#print axioms CausalGeometry.LinearInvariant.core_idempotent
#print axioms CausalGeometry.LinearInvariant.restrict_map_val
#print axioms CausalGeometry.PersistentLinear.defect_apply
#print axioms CausalGeometry.PersistentLinear.mem_domain
#print axioms CausalGeometry.PersistentLinear.domain_stable
#print axioms CausalGeometry.PersistentLinear.domain_core
#print axioms CausalGeometry.PersistentLinear.domain_maximal
#print axioms CausalGeometry.PersistentLinear.domain_eq_top_of_natural
#print axioms CausalGeometry.PersistentLinear.composition_domain
#print axioms CausalGeometry.PersistentLinear.observation_domain
#print axioms CausalGeometry.LinearInvariant.Paths.stable_of_steps
#print axioms CausalGeometry.LinearInvariant.Paths.persistent_eq_core_generators
#print axioms CausalGeometry.LinearInvariant.Paths.le_persistent_of_steps
#print axioms CausalGeometry.LinearInvariant.Paths.prune_le
#print axioms CausalGeometry.LinearInvariant.Paths.prune_mono
#print axioms CausalGeometry.LinearInvariant.Paths.horizon_le
#print axioms CausalGeometry.LinearInvariant.Paths.horizon_descending
#print axioms CausalGeometry.LinearInvariant.Paths.core_le_horizon
#print axioms CausalGeometry.LinearInvariant.Paths.horizon_fixed_eq_core
#print axioms CausalGeometry.Exchange.Persistent.mem_domain
#print axioms CausalGeometry.Exchange.Persistent.stable
#print axioms CausalGeometry.Exchange.Persistent.domain_eq_core
#print axioms CausalGeometry.Exchange.Persistent.domain_top_of_intertwines
#print axioms CausalGeometry.Exchange.Persistent.composition_safe
#print axioms CausalGeometry.Exchange.Persistent.sourceRoundTrip_safe
#print axioms CausalGeometry.Exchange.Persistent.targetRoundTrip_safe
#print axioms CausalGeometry.Exchange.Persistent.basis_mem_iff
#print axioms CausalGeometry.Exchange.Persistent.span_states_le
#print axioms CausalGeometry.Exchange.Persistent.step_constant
#print axioms CausalGeometry.Exchange.Persistent.map_constant
#print axioms CausalGeometry.Exchange.Persistent.route_constant
#print axioms CausalGeometry.Exchange.Persistent.constant_basis_mem
#print axioms CausalGeometry.Models.ExchangePersistentControls.constant_is_persistent
#print axioms CausalGeometry.Models.ExchangePersistentControls.constant_basis_nonzero
#print axioms CausalGeometry.Models.ExchangePersistentControls.middle_not_persistent
#print axioms CausalGeometry.Models.ExchangePersistentControls.persistent_nonzero_proper
#print axioms CausalGeometry.Models.ExchangePersistentControls.middle_locally_compatible
#print axioms CausalGeometry.Models.ExchangePersistentControls.middle_delayed_failure
#print axioms CausalGeometry.Models.ExchangePersistentControls.outgoing_kernels_are_not_persistent_domain
#print axioms CausalGeometry.Models.ExchangePersistentControls.composition_inclusion_can_be_strict
#print axioms CausalGeometry.Models.ExchangePersistentControls.lossy_observation_has_full_domain
#print axioms CausalGeometry.LinearInvariant.restrict
#print axioms CausalGeometry.LinearInvariant.inclusion
#print axioms CausalGeometry.PersistentLinear.transport
#print axioms CausalGeometry.Models.ExchangeLinearDefectControls.causal_defect_nonzero
