import CausalGeometry.History.EventList

/-!
# Contextual exchanges of actual causal histories

A witness lives in Type and contains a real enabled diamond and its contexts.
The equalities below certify the decomposition of the two input paths. They
are not equations between exchange routes. Neither inverses nor Yang–Baxter
are imposed on the free paths generated by these witnesses.
-/
namespace CausalGeometry.Exchange

universe u v
open CausalGeometry EventSystem CausalVariational

variable {Event : Type u} {Label : Type v}
variable {S : EventSystem Event Label}

/-- One oriented chronological swap, with an actual location and contexts. -/
structure Step {C D : Configuration S} (p q : CausalPath S C D) where
  pivot : Configuration S
  first : Event
  second : Event
  diamond : ConcurrencyDiamond pivot first second
  prefix : CausalPath S C pivot
  suffix : CausalPath S diamond.afterEF D
  source_eq : prefix.comp ((diamondPathEF diamond).comp suffix) = p
  target_eq : prefix.comp ((diamondPathFE diamond).comp suffix) = q

namespace Step

/-- The position is derived from the causal prefix, never a free label. -/
def position {C D : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) : Nat := s.prefix.length

/-- Immediate swap at the start of a history. -/
def atDiamond {C D : Configuration S} {e f : Event}
    (d : ConcurrencyDiamond C e f) (tail : CausalPath S d.afterEF D) :
    Step ((diamondPathEF d).comp tail) ((diamondPathFE d).comp tail) where
  pivot := C
  first := e
  second := f
  diamond := d
  prefix := .nil C
  suffix := tail
  source_eq := rfl
  target_eq := rfl

@[simp] theorem atDiamond_position {C D : Configuration S} {e f : Event}
    (d : ConcurrencyDiamond C e f) (tail : CausalPath S d.afterEF D) :
    (atDiamond d tail).position = 0 := rfl

/-- Prefixing a valid history gives another actual exchange witness. -/
def whiskerLeft {A C D : Configuration S} {p q : CausalPath S C D}
    (r : CausalPath S A C) (s : Step p q) : Step (r.comp p) (r.comp q) where
  pivot := s.pivot
  first := s.first
  second := s.second
  diamond := s.diamond
  prefix := r.comp s.prefix
  suffix := s.suffix
  source_eq := by rw [CausalPath.comp_assoc, s.source_eq]
  target_eq := by rw [CausalPath.comp_assoc, s.target_eq]

/-- Suffixing a valid continuation preserves both endpoints and the pivot. -/
def whiskerRight {C D E : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) (r : CausalPath S D E) : Step (p.comp r) (q.comp r) where
  pivot := s.pivot
  first := s.first
  second := s.second
  diamond := s.diamond
  prefix := s.prefix
  suffix := s.suffix.comp r
  source_eq := by
    simpa only [CausalPath.comp_assoc] using
      congrArg (fun t => t.comp r) s.source_eq
  target_eq := by
    simpa only [CausalPath.comp_assoc] using
      congrArg (fun t => t.comp r) s.target_eq

@[simp] theorem whiskerLeft_position
    {A C D : Configuration S} {p q : CausalPath S C D}
    (r : CausalPath S A C) (s : Step p q) :
    (whiskerLeft r s).position = r.length + s.position := by
  exact CausalPath.length_comp r s.prefix

@[simp] theorem whiskerRight_position
    {C D E : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) (r : CausalPath S D E) :
    (s.whiskerRight r).position = s.position := rfl

/-- An exchange conserves the number of executed occurrences. -/
theorem length_eq {C D : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) : p.length = q.length := by
  rw [← s.source_eq, ← s.target_eq]
  simp only [CausalPath.length_comp, diamondPathEF_length, diamondPathFE_length]

/-- Its index is strictly inside the executed word, with two available slots. -/
theorem position_bound {C D : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) : s.position + 2 ≤ p.length := by
  rw [← s.source_eq]
  simp only [position, CausalPath.length_comp, diamondPathEF_length]
  omega

/-- Same-type failing mutation: no exchange can carry conflicting events. -/
theorem not_conflict {C D : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) : ¬ S.conflict s.first s.second :=
  s.diamond.concurrent.2.2.2.2.1

theorem distinct_occurrences {C D : Configuration S} {p q : CausalPath S C D}
    (s : Step p q) : s.first ≠ s.second :=
  s.diamond.concurrent.2.2.2.2.2

end Step
end CausalGeometry.Exchange
