import CausalGeometry.Foundation.AdjunctionBridge
import CausalGeometry.Calculus.StructuralTransport

namespace CausalGeometry

universe u v w

namespace AdjointVariation

variable {α : Type u} {β : Type v} {V : Type w}
variable [Preorder α] [Preorder β]

/-- Observable variation generated by the closure Psi(Phi(-)) once a structural
pair has additionally been proved adjoint. -/
def closureDifference [AddGroup V]
    (P : PairedTransform α β)
    (_A : AdjointBridge P)
    (F : α → V) (a : α) : V :=
  StructuralVariation.sourceRoundTripDifference P F a

/-- Observable variation generated by the realizable interior Phi(Psi(-)). -/
def interiorDifference [AddGroup V]
    (P : PairedTransform α β)
    (_A : AdjointBridge P)
    (F : β → V) (b : β) : V :=
  StructuralVariation.targetRoundTripDifference P F b

theorem closureDifference_eq_zero_of_fixed [AddGroup V]
    (P : PairedTransform α β)
    (A : AdjointBridge P)
    (F : α → V) {a : α}
    (h : P.SourceFixed a) :
    closureDifference P A F a = 0 :=
  StructuralVariation.sourceRoundTripDifference_eq_zero_of_fixed P F h

theorem interiorDifference_eq_zero_of_fixed [AddGroup V]
    (P : PairedTransform α β)
    (A : AdjointBridge P)
    (F : β → V) {b : β}
    (h : P.TargetFixed b) :
    interiorDifference P A F b = 0 :=
  StructuralVariation.targetRoundTripDifference_eq_zero_of_fixed P F h

/-- The adjunction bridge recovers exactly the pre-existing closure operator. -/
theorem sourceRoundTrip_eq_extensionRestriction_closure
    (P : PairedTransform α β)
    (A : AdjointBridge P) (a : α) :
    P.sourceRoundTrip a =
      (A.toExtensionRestriction).closure a := by
  rfl

/-- The adjunction bridge recovers exactly the pre-existing interior operator. -/
theorem targetRoundTrip_eq_extensionRestriction_interior
    (P : PairedTransform α β)
    (A : AdjointBridge P) (b : β) :
    P.targetRoundTrip b =
      (A.toExtensionRestriction).interior b := by
  rfl

end AdjointVariation
end CausalGeometry
