import CausalGeometry.Calculus.CubicalDifferentialSquared
import CausalGeometry.Calculus.EventHodge
import Mathlib.Tactic

namespace CausalGeometry

universe u v w

open EventSystem

variable {Event : Type u} {Label : Type v}
variable {S : EventSystem Event Label}

namespace CausalEventCube

/-- Every zero-cube is the canonical zeroCube on its base. -/
theorem zeroCube_base_eq
    (Q : CausalEventCube S 0) :
    zeroCube Q.base = Q := by
  apply CausalEventCube.ext
  · rfl
  · funext i
    exact Fin.elim0 i

/-- The unique primitive direction carried by a one-cube. -/
def direction0
    (Q : CausalEventCube S 1) :
    EventDirection S Q.base where
  event := Q.frame.event 0
  enabled := Q.frame.enabled 0

@[simp] theorem direction0_event
    (Q : CausalEventCube S 1) :
    Q.direction0.event =
      Q.frame.event 0 :=
  rfl

/-- Every one-cube is the canonical oneCube generated by its unique
direction. -/
theorem oneCube_direction0_eq
    (Q : CausalEventCube S 1) :
    oneCube Q.base
        Q.direction0.event
        Q.direction0.enabled
      =
    Q := by
  apply CausalEventCube.ext
  · rfl
  · funext i
    have hi : i = (0 : Fin 1) :=
      Subsingleton.elim _ _
    subst i
    rfl

/-- Ordered concurrency diamond canonically carried by a two-cube. -/
def diamond01
    (Q : CausalEventCube S 2) :
    ConcurrencyDiamond
      Q.base
      (Q.frame.event 0)
      (Q.frame.event 1) :=
  Q.frame.diamond (by decide)

/-- Construct the ordered two-cube associated to one concurrency diamond. -/
def ofDiamond
    {C : Configuration S}
    {e f : Event}
    (d : ConcurrencyDiamond C e f) :
    CausalEventCube S 2 :=
  ⟨C,
    { event := fun i =>
        Fin.cases e (fun _ => f) i
      enabled := fun i =>
        Fin.cases d.concurrent.1
          (fun _ => d.concurrent.2.1) i
      injective := by
        intro i j h
        fin_cases i <;> fin_cases j
        · rfl
        · exfalso
          exact d.concurrent.2.2.2.2.2 h
        · exfalso
          exact d.concurrent.2.2.2.2.2 h.symm
        · rfl
      independent := by
        intro i j hij
        fin_cases i <;> fin_cases j
        · exact (hij rfl).elim
        · exact
            ⟨d.concurrent.2.2.1,
              d.concurrent.2.2.2.1,
              d.concurrent.2.2.2.2.1⟩
        · exact
            ⟨d.concurrent.2.2.2.1,
              d.concurrent.2.2.1,
              fun h =>
                d.concurrent.2.2.2.2.1
                  (S.conflict_symm h)⟩
        · exact (hij rfl).elim }⟩

@[simp] theorem ofDiamond_base
    {C : Configuration S}
    {e f : Event}
    (d : ConcurrencyDiamond C e f) :
    (ofDiamond d).base = C :=
  rfl

@[simp] theorem ofDiamond_event_zero
    {C : Configuration S}
    {e f : Event}
    (d : ConcurrencyDiamond C e f) :
    (ofDiamond d).frame.event 0 = e :=
  rfl

@[simp] theorem ofDiamond_event_one
    {C : Configuration S}
    {e f : Event}
    (d : ConcurrencyDiamond C e f) :
    (ofDiamond d).frame.event 1 = f :=
  rfl

/-- Going diamond -> two-cube -> ordered diamond changes only proof witnesses,
hence is definitionally the same causal diamond by proof irrelevance. -/
theorem diamond01_ofDiamond
    {C : Configuration S}
    {e f : Event}
    (d : ConcurrencyDiamond C e f) :
    (ofDiamond d).diamond01 = d := by
  cases d
  rfl

/-- Going two-cube -> diamond -> two-cube recovers the original cube. -/
theorem ofDiamond_diamond01
    (Q : CausalEventCube S 2) :
    ofDiamond Q.diamond01 = Q := by
  apply CausalEventCube.ext
  · rfl
  · funext i
    fin_cases i <;> rfl

end CausalEventCube

namespace CausalCubicalCochain

variable {K : Type w} [Field K]

/-- Recover a scalar configuration observable from a degree-zero cubical
cochain. -/
def toConfigurationObservable
    (ω : CausalCubicalCochain S K 0) :
    Configuration S → K :=
  fun C => ω (CausalEventCube.zeroCube C)

/-- Degree zero is linearly equivalent to the pre-existing configuration
observable carrier. -/
def degreeZeroLinearEquiv :
    (Configuration S → K) ≃ₗ[K]
      CausalCubicalCochain S K 0 where
  toFun :=
    ofConfigurationObservable
  invFun :=
    toConfigurationObservable
  left_inv := by
    intro F
    funext C
    rfl
  right_inv := by
    intro ω
    funext Q
    rw [← CausalEventCube.zeroCube_base_eq Q]
    rfl
  map_add' := by
    intro F G
    rfl
  map_smul' := by
    intro a F
    rfl

/-- Evaluate an old causal one-form on the unique direction carried by a
one-cube. -/
def ofOneForm
    (ω : CausalOneForm S K) :
    CausalCubicalCochain S K 1 :=
  fun Q =>
    ω.value Q.base Q.direction0

/-- Recover a causal one-form from a degree-one cubical cochain. -/
def toOneForm
    (α : CausalCubicalCochain S K 1) :
    CausalOneForm S K where
  value := fun C d =>
    α (CausalEventCube.oneCube
      C d.event d.enabled)

/-- Degree one is linearly equivalent to the existing CausalOneForm carrier. -/
def degreeOneLinearEquiv :
    CausalOneForm S K ≃ₗ[K]
      CausalCubicalCochain S K 1 where
  toFun := ofOneForm
  invFun := toOneForm
  left_inv := by
    intro ω
    apply CausalOneForm.ext
    intro C d
    rfl
  right_inv := by
    intro α
    funext Q
    rw [← CausalEventCube.oneCube_direction0_eq Q]
    rfl
  map_add' := by
    intro ω η
    funext Q
    rfl
  map_smul' := by
    intro a ω
    funext Q
    rfl

/-- Evaluate an old raw degree-two cochain on the ordered diamond carried by a
two-cube. -/
def ofRawTwoCochain
    (η : CausalCohomology.RawTwoCochain S K) :
    CausalCubicalCochain S K 2 :=
  fun Q =>
    η Q.base
      (Q.frame.event 0)
      (Q.frame.event 1)
      Q.diamond01

/-- Recover an old raw degree-two cochain from the corresponding canonical
ordered two-cube. -/
def toRawTwoCochain
    (α : CausalCubicalCochain S K 2) :
    CausalCohomology.RawTwoCochain S K :=
  fun _ _ _ d =>
    α (CausalEventCube.ofDiamond d)

/-- Degree two raw cubical cochains are linearly equivalent to the old
RawTwoCochain carrier. -/
def degreeTwoLinearEquiv :
    CausalCohomology.RawTwoCochain S K ≃ₗ[K]
      CausalCubicalCochain S K 2 where
  toFun := ofRawTwoCochain
  invFun := toRawTwoCochain
  left_inv := by
    intro η
    funext C e f d
    rw [CausalEventCube.diamond01_ofDiamond]
  right_inv := by
    intro α
    funext Q
    rw [CausalEventCube.ofDiamond_diamond01]
  map_add' := by
    intro η θ
    funext Q
    rfl
  map_smul' := by
    intro a η
    funext Q
    rfl

/-- Four evaluations of a one-form cubical cochain on a two-cube are exactly
the four terms appearing in the existing exterior derivative. -/
@[simp] theorem ofOneForm_upper_zero
    (ω : CausalOneForm S K)
    (Q : CausalEventCube S 2) :
    ofOneForm ω (Q.upperFace (0 : Fin 2)) =
      ω.value Q.diamond01.afterE
        (CausalOneForm.afterE_F Q.diamond01) := by
  rfl

@[simp] theorem ofOneForm_lower_zero
    (ω : CausalOneForm S K)
    (Q : CausalEventCube S 2) :
    ofOneForm ω (Q.lowerFace (0 : Fin 2)) =
      ω.value Q.base
        (CausalOneForm.baseF Q.diamond01) := by
  rfl

@[simp] theorem ofOneForm_upper_one
    (ω : CausalOneForm S K)
    (Q : CausalEventCube S 2) :
    ofOneForm ω (Q.upperFace (1 : Fin 2)) =
      ω.value Q.diamond01.afterF
        (CausalOneForm.afterF_E Q.diamond01) := by
  rfl

@[simp] theorem ofOneForm_lower_one
    (ω : CausalOneForm S K)
    (Q : CausalEventCube S 2) :
    ofOneForm ω (Q.lowerFace (1 : Fin 2)) =
      ω.value Q.base
        (CausalOneForm.baseE Q.diamond01) := by
  rfl

/-- Degree-zero commuting square: the new cubical differential is the old
causal exact-one-form differential under the degree-zero/degree-one carrier
equivalences. -/
theorem differential_zero_eq_d0Linear
    (F : Configuration S → K) :
    differential (S := S) (K := K) 0
        (degreeZeroLinearEquiv
          (S := S) (K := K) F)
      =
    degreeOneLinearEquiv
      (S := S) (K := K)
      (CausalCohomology.d0Linear
        (S := S) (K := K) F) := by
  funext Q
  rw [← CausalEventCube.oneCube_direction0_eq Q]
  exact
    differential_zero_recovers_causalDifference
      F Q.base
      Q.direction0.event
      Q.direction0.enabled

/-- Degree-one commuting square: the arbitrary cubical differential recovers
the existing exterior derivative exactly. -/
theorem differential_one_eq_d1Linear
    (ω : CausalOneForm S K) :
    differential (S := S) (K := K) 1
        (degreeOneLinearEquiv
          (S := S) (K := K) ω)
      =
    degreeTwoLinearEquiv
      (S := S) (K := K)
      (CausalCohomology.d1Linear
        (S := S) (K := K) ω) := by
  funext Q
  rw [differential_apply, Fin.sum_univ_two]
  simp only [faceContribution, faceSign]
  rw [
    ofOneForm_upper_zero,
    ofOneForm_lower_zero,
    ofOneForm_upper_one,
    ofOneForm_lower_one
  ]
  norm_num
  rfl

/-- The old concrete event cochain complex is therefore exactly the 0-1-2
truncation of the new arbitrary-degree causal cubical complex, up to the three
explicit linear carrier equivalences above. -/
theorem old_event_complex_is_cubical_truncation :
    (∀ F : Configuration S → K,
      differential (S := S) (K := K) 0
          (degreeZeroLinearEquiv
            (S := S) (K := K) F)
        =
      degreeOneLinearEquiv
        (S := S) (K := K)
        (CausalCohomology.d0Linear
          (S := S) (K := K) F))
    ∧
    (∀ ω : CausalOneForm S K,
      differential (S := S) (K := K) 1
          (degreeOneLinearEquiv
            (S := S) (K := K) ω)
        =
      degreeTwoLinearEquiv
        (S := S) (K := K)
        (CausalCohomology.d1Linear
          (S := S) (K := K) ω)) := by
  constructor
  · exact differential_zero_eq_d0Linear
  · exact differential_one_eq_d1Linear

end CausalCubicalCochain
end CausalGeometry
