import CausalGeometry.Realization.Family

namespace CausalGeometry

universe u v w x

/-- A place-indexed family of typed realizations of one common source type.

For every place `place`, the target carrier may be different, but every
local value is obtained from the same source object.  This is the source-side
infrastructure needed before adelic, elliptic or local-global consumers can
claim that their local packets have common provenance. -/
structure IndexedRealizationFamily
    (α : Type u)
    (Place : Type v) where
  Target : Place → Type w
  realize :
    (place : Place) →
      α → Target place

namespace IndexedRealizationFamily

variable
    {α : Type u}
    {Place : Type v}

instance
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (place : Place) :
    CoeFun R (fun _ => α → R.Target place) :=
  ⟨R.realize place⟩

/-- Value of one common source at one selected place. -/
def value
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (x : α)
    (place : Place) :
    R.Target place :=
  R.realize place x

/-- The complete dependent local packet generated by one source object. -/
def packet
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (x : α) :
    (place : Place) → R.Target place :=
  fun place => R.realize place x

/-- A placewise typed comparison between two local realization families.

The comparison must commute for every source object and every place. -/
structure Comparison
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (S : IndexedRealizationFamily.{u, v, x}
      α Place) where
  map :
    (place : Place) →
      R.Target place →
        S.Target place
  commutes :
    ∀ (source : α) (place : Place),
      map place (R.realize place source) =
        S.realize place source

namespace Comparison

def id
    (R : IndexedRealizationFamily.{u, v, w}
      α Place) :
    Comparison R R where
  map := fun _ => id
  commutes := by
    intro source place
    rfl

def comp
    {R : IndexedRealizationFamily.{u, v, w}
      α Place}
    {S : IndexedRealizationFamily.{u, v, x}
      α Place}
    {y : Level}
    {T : IndexedRealizationFamily.{u, v, y}
      α Place}
    (η : Comparison R S)
    (θ : Comparison S T) :
    Comparison R T where
  map :=
    fun place =>
      θ.map place ∘ η.map place
  commutes := by
    intro source place
    rw [
      Function.comp_apply,
      η.commutes source place,
      θ.commutes source place
    ]

end Comparison

/-- Two source objects collapse at one selected place. -/
def CollapsesAt
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (place : Place)
    (x y : α) : Prop :=
  R.realize place x =
    R.realize place y

/-- Two source objects collapse in the complete local family. -/
def CollapsesEverywhere
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (x y : α) : Prop :=
  ∀ place,
    R.CollapsesAt place x y

/-- A placewise comparison can only increase information loss at each place. -/
theorem collapseAt_of_comparison
    {R : IndexedRealizationFamily.{u, v, w}
      α Place}
    {S : IndexedRealizationFamily.{u, v, x}
      α Place}
    (η : Comparison R S)
    {source₁ source₂ : α}
    (place : Place)
    (h :
      R.CollapsesAt place
        source₁ source₂) :
    S.CollapsesAt place
      source₁ source₂ := by
  unfold CollapsesAt at h ⊢
  rw [
    ← η.commutes source₁ place,
    ← η.commutes source₂ place,
    h
  ]

/-- A placewise comparison can only increase information loss globally. -/
theorem collapseEverywhere_of_comparison
    {R : IndexedRealizationFamily.{u, v, w}
      α Place}
    {S : IndexedRealizationFamily.{u, v, x}
      α Place}
    (η : Comparison R S)
    {source₁ source₂ : α}
    (h :
      R.CollapsesEverywhere
        source₁ source₂) :
    S.CollapsesEverywhere
      source₁ source₂ := by
  intro place
  exact η.collapseAt_of_comparison
    place (h place)

/-- A local realization family is jointly conservative when agreement at all
places recovers the source object.

This is deliberately a separate property: common provenance does not imply
local-to-global reconstruction. -/
def JointlyConservative
    (R : IndexedRealizationFamily.{u, v, w}
      α Place) : Prop :=
  ∀ x y,
    R.CollapsesEverywhere x y →
      x = y

/-- Restrict a common-source family to a proved source domain without changing
any local target.

Using a subtype keeps admissibility proofs out of the mathematical local
packet and makes proof irrelevance automatic. -/
def restrict
    (R : IndexedRealizationFamily.{u, v, w}
      α Place)
    (Domain : α → Prop) :
    IndexedRealizationFamily
      {x : α // Domain x} Place where
  Target := R.Target
  realize :=
    fun place x =>
      R.realize place x.1

end IndexedRealizationFamily
end CausalGeometry
