import CausalGeometry.Calculus.SymplecticGeometry
import CausalGeometry.Calculus.HamiltonianEventEquation
import Mathlib.Tactic

namespace CausalGeometry

universe u v w x y
open EventSystem

variable {Event : Type u} {Label : Type v}
variable {S : EventSystem Event Label}

namespace CausalVariational

variable {K : Type w}
variable {Fiber : Configuration S → Type x}
variable [CommRing K]
variable [∀ C, AddCommGroup (Fiber C)]
variable [∀ C, Module K (Fiber C)]

/-- A causal momentum map for a family of symmetry generators.

Each generator xi is represented by a Hamiltonian vector section together
with a scalar momentum potential J_xi satisfying

  i_(X_xi) omega = d_C J_xi

on all soldered primitive event directions. -/
structure MomentumMap
    (G : CausalSymplecticGeometry K S Fiber)
    (Gen : Type y) where

  component :
    Gen →
      CausalHamiltonian.PotentialPair
        G.symplectic.toField
        G.soldering

namespace MomentumMap

variable
    {G : CausalSymplecticGeometry K S Fiber}
    {Gen : Type y}
    (J : MomentumMap G Gen)

/-- Infinitesimal/vector generator associated to one symmetry label. -/
def generator
    (xi : Gen) :
    CausalHamiltonian.VectorSection
      (S := S) (Fiber := Fiber) :=
  (J.component xi).toPair.vector

/-- Scalar momentum/current associated to one symmetry label. -/
def momentum
    (xi : Gen) :
    Configuration S → K :=
  (J.component xi).potential

/-- Covector differential of the momentum component. -/
def momentumCovector
    (xi : Gen) :
    CausalHamiltonian.CovectorSection
      (K := K) (S := S) (Fiber := Fiber) :=
  (J.component xi).toPair.covector

/-- Event-level momentum equation:
omega(X_xi, theta(d)) = d_C J_xi(d). -/
theorem eventMomentumEquation
    (xi : Gen)
    (C : Configuration S)
    (d : EventDirection S C) :
    G.symplectic.toField.form C
        (J.generator xi C)
        (G.soldering.vector C d)
      =
    causalDifference
      (J.momentum xi)
      C d.event d.enabled := by
  exact
    (J.component xi).eventHamiltonEquation
      C d

/-- Hamiltonian invariance of an evolution pair against one symmetry generator
at one configuration.

This is the finite causal analogue of {H,J_xi}=0 or dH(X_xi)=0. -/
def HamiltonianInvariantAt
    (H :
      CausalHamiltonian.Pair
        G.symplectic.toField)
    (xi : Gen)
    (C : Configuration S) : Prop :=
  G.symplectic.toField.form C
      (H.vector C)
      (J.generator xi C)
    =
  0

/-- Causal Noether momentum conservation.

If the Hamiltonian evolution vector is generated by one primitive causal event
direction and the Hamiltonian is invariant against symmetry generator xi, then
the corresponding momentum component has zero causal difference along that
event. -/
theorem momentum_conserved_on_generated_event
    (H :
      CausalHamiltonian.Pair
        G.symplectic.toField)
    (xi : Gen)
    (C : Configuration S)
    (d : EventDirection S C)
    (hgen :
      H.vector C =
        G.soldering.vector C d)
    (hinv :
      J.HamiltonianInvariantAt H xi C) :
    causalDifference
        (J.momentum xi)
        C d.event d.enabled
      =
    0 := by

  rw [← J.eventMomentumEquation xi C d]
  rw [← hgen]

  have hskew :=
    G.symplectic.toField.skew_of_alternating
      G.symplectic.alternating
      C
      (H.vector C)
      (J.generator xi C)

  change
    G.symplectic.toField.form C
        (J.generator xi C)
        (H.vector C)
      =
    0

  rw [hskew]
  rw [hinv]
  simp

/-- Equivalent formulation: the momentum current is locally conserved exactly
when its symplectic contraction with the event-generated Hamiltonian vector
vanishes. -/
theorem momentumDifference_eq_symplecticPair
    (H :
      CausalHamiltonian.Pair
        G.symplectic.toField)
    (xi : Gen)
    (C : Configuration S)
    (d : EventDirection S C)
    (hgen :
      H.vector C =
        G.soldering.vector C d) :
    causalDifference
        (J.momentum xi)
        C d.event d.enabled
      =
    G.symplectic.toField.form C
      (J.generator xi C)
      (H.vector C) := by
  rw [← J.eventMomentumEquation xi C d]
  rw [hgen]

/-- Conservation predicate along a specific enabled event. -/
def MomentumConservedAt
    (xi : Gen)
    (C : Configuration S)
    (d : EventDirection S C) : Prop :=
  causalDifference
      (J.momentum xi)
      C d.event d.enabled
    =
  0

theorem hamiltonianInvariant_implies_momentumConserved
    (H :
      CausalHamiltonian.Pair
        G.symplectic.toField)
    (xi : Gen)
    (C : Configuration S)
    (d : EventDirection S C)
    (hgen :
      H.vector C =
        G.soldering.vector C d)
    (hinv :
      J.HamiltonianInvariantAt H xi C) :
    J.MomentumConservedAt xi C d :=
  J.momentum_conserved_on_generated_event
    H xi C d hgen hinv

/-- If a symmetry momentum is conserved on every event of a finite causal path,
its endpoint values agree.

This turns the local Noether law into a pathwise conserved current. -/
theorem momentum_endpoint_eq_of_path_conserved :
    ∀ {C D : Configuration S}
      (p : CausalPath S C D)
      (xi : Gen),
      (∀ {C0 C1 : Configuration S}
        (e : Event)
        (h : S.Enabled C0 e)
        (tail : CausalPath S
          (S.extend C0 e h) C1),
        causalDifference
            (J.momentum xi)
            C0 e h
          =
        0) →
      J.momentum xi D =
        J.momentum xi C := by
  intro C D p xi hcons
  induction p with
  | nil =>
      rfl
  | @step C D e h tail ih =>
      have hstep :=
        hcons e h tail
      unfold causalDifference at hstep
      have hlocal :
          J.momentum xi (S.extend C e h) =
            J.momentum xi C :=
        sub_eq_zero.mp hstep
      rw [ih]
      exact hlocal

end MomentumMap
end CausalVariational
end CausalGeometry
